"""initial migration

Revision ID: b7e444c592fc
Revises: 
Create Date: 2026-04-26 20:55:39.025048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7e444c592fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('linkedin', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('residence_zone', sa.Enum('AMBA', 'BSAS_AMPLIO', 'ROSARIO_PERIFERIA', 'SANTA_FE', 'CATAMARCA', 'CHACO', 'CHUBUT', 'CORDOBA', 'CORRIENTES', 'ENTRE_RIOS', 'FORMOSA', 'JUJUY', 'LA_PAMPA', 'LA_RIOJA', 'MENDOZA', 'MISIONES', 'NEUQUEN', 'RIO_NEGRO', 'SALTA', 'SAN_JUAN', 'SAN_LUIS', 'SANTA_CRUZ', 'SANTIAGO_DEL_ESTERO', 'TIERRA_DEL_FUEGO', 'TUCUMAN', name='residencezone'), nullable=True),
    sa.Column('salary_expectation', sa.Integer(), nullable=True),
    sa.Column('notice_period_weeks', sa.Enum('ONE_WEEK', 'TWO_WEEKS', 'THREE_WEEKS', 'FOUR_WEEKS', name='noticeperiod'), nullable=True),
    sa.Column('part_time_desired', sa.Boolean(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SELECTOR', 'HEAD', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_unit', sa.Enum('RENAISS', 'STAFFED', name='businesstype'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title_seniority', sa.String(), nullable=False),
    sa.Column('salary_range', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('CLOUDSSR', 'CLOUDSR', 'DEVSSR', 'DEVSR', 'OtherJobs', name='categoryjob'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVA', 'PAUSADA', 'CERRADA', 'CANCELADA', name='jobstatus'), nullable=False),
    sa.Column('open_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('HUNTING', 'APPLY', 'REFERRED', name='applicationsource'), nullable=False),
    sa.Column('selector_id', sa.UUID(), nullable=True),
    sa.Column('general_status', sa.Enum('CONTACTADO_SIN_RESP', 'EN_CONVERSACION', 'EN_PROCESO', 'NO_INICIA', 'NO_CONTINUA', 'INGRESO', name='generalstatus'), nullable=False),
    sa.Column('process_stage', sa.Enum('HR', 'CC', 'SD', 'CF', 'REUNION_CLIENTE', 'PSICOTECNICO', 'OFFER', 'ENTREVISTA', 'PRUEBA_TECNICA', 'ENTREVISTA_CLIENTE', name='processstage'), nullable=True),
    sa.Column('sub_status_rejection', sa.Enum('FALTA_STACK', 'SIN_INGLES', 'FALTA_SENIORITY', 'NO_INTERESA', 'BUSCA_PART_TIME', 'BUSCA_MAYOR_SUELDO', 'DESISTE', 'MAL_HR', 'MAL_CC', 'MAL_SD', 'MAL_CF', 'MAL_ENTREVISTA_CLIENTE', 'MAL_PSICOTECNICO', name='substatusrejection'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('start_process_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_presentation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['selector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('keep_alive_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keep_alive_log',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='keep_alive_log_pkey')
    )
    op.drop_table('applications')
    op.drop_table('jobs')
    op.drop_table('users')
    op.drop_table('companies')
    op.drop_table('candidates')
    # ### end Alembic commands ###
